# Generated by Django 5.2.8 on 2026-01-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='scanned_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('correct_answers', models.JSONField(default=dict)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='test_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='myapp.class')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='myapp.test'),
        ),
    ]
